package by.epam.finaltask.facultative.command;


public enum CommandName {
    LOGIN,
    APPLY,
    REGISTRATION_STUDENT,
    REGISTRATION_TEACHER,
    STUDENTGROUP,
    UPDATE,
    BACK,
    SIGN_OUT,
    SAVE_USER,
    UPDATE_USER,
    COURSE,
    DELETE_COURSE_STUDENT,
    DELETE_COURSE_TEACHER,
    STUDENT_COURSE,
    TEACHER_COURSE,
    ALL_COURSES_FOR_STUDENT,
    ALL_COURSES,
    ADD_COURSE;
}
